name: Get new udemy courses every 6 hours

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours

env:
  # Setting an environment variable with the value of a configuration variable
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content
        with:
          node-version: '20'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          cache: 'pip'
          node-version: '20'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: |
          python cli.py
